In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten

In [3]:
data = pd.read_csv("CricketData.csv")
data.head()

Date     Type  Pos  Neg  Neu
0  18-03-2021  Cricket  506   88  406
1  19-03-2021  Cricket  449   88  463
2  20-03-2021  Cricket  392   88  520
3  21-03-2021  Cricket  754   10  236
4  22-03-2021  Cricket  627   30  343

# Pos LSTM

In [4]:
def prepare_data(data,n_step):
    x,y=[],[]
    for i in range(len(data)):
        end_ix = i + n_step
        if end_ix > len(data)-1:
            break
        seq_x, seq_y = data[i:end_ix], data[end_ix]
        x.append(seq_x)
        y.append(seq_y)
    return np.array(x), np.array(y)

In [5]:
Pos_data = data.Pos
n_step = 3
x,y = prepare_data(Pos_data, n_step)

In [6]:
print(x)

[[506 449 392]
 [449 392 754]
 [392 754 627]
 [754 627 500]
 [627 500 535]
 [500 535 535]
 [535 535 571]
 [535 571 483]
 [571 483 396]
 [483 396 300]
 [396 300 204]
 [300 204 170]
 [204 170 308]
 [170 308 556]
 [308 556 132]
 [556 132 496]
 [132 496 496]
 [496 496 861]
 [496 861 748]
 [861 748 748]
 [748 748 636]
 [748 636 363]
 [636 363 484]
 [363 484 510]
 [484 510 588]
 [510 588 292]
 [588 292 389]
 [292 389 374]
 [389 374 659]
 [374 659 710]
 [659 710 578]]


In [7]:
print(y)

[754 627 500 535 535 571 483 396 300 204 170 308 556 132 496 496 861 748
 748 636 363 484 510 588 292 389 374 659 710 578 465]


In [85]:
x.shape

(31, 3)

In [86]:
n_features = 1
x = x.reshape((x.shape[0], x.shape[1], n_features))

In [87]:
x.shape

(31, 3, 1)

In [92]:
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_step, n_features)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
model.fit(x,y,epochs=900, verbose=1)

Epoch 1/900
1/1 - 0s - loss: 283434.7188
Epoch 2/900
1/1 - 0s - loss: 281825.9375
Epoch 3/900
1/1 - 0s - loss: 280427.2812
Epoch 4/900
1/1 - 0s - loss: 279344.6562
Epoch 5/900
1/1 - 0s - loss: 278498.0312
Epoch 6/900
1/1 - 0s - loss: 277423.4062
Epoch 7/900
1/1 - 0s - loss: 276329.1875
Epoch 8/900
1/1 - 0s - loss: 275408.9062
Epoch 9/900
1/1 - 0s - loss: 274036.8125
Epoch 10/900
1/1 - 0s - loss: 272531.6875
Epoch 11/900
1/1 - 0s - loss: 270971.0000
Epoch 12/900
1/1 - 0s - loss: 269366.4688
Epoch 13/900
1/1 - 0s - loss: 266995.6250
Epoch 14/900
1/1 - 0s - loss: 262860.3438
Epoch 15/900
1/1 - 0s - loss: 260369.5469
Epoch 16/900
1/1 - 0s - loss: 257808.5469
Epoch 17/900
1/1 - 0s - loss: 255042.5312
Epoch 18/900
1/1 - 0s - loss: 252051.0781
Epoch 19/900
1/1 - 0s - loss: 249117.3281
Epoch 20/900
1/1 - 0s - loss: 246069.5000
Epoch 21/900
1/1 - 0s - loss: 240581.6719
Epoch 22/900
1/1 - 0s - loss: 234257.5781
Epoch 23/900
1/1 - 0s - loss: 228665.3281
Epoch 24/900
1/1 - 0s - loss: 223855.3594
E

Epoch 198/900
1/1 - 0s - loss: 12275.0283
Epoch 199/900
1/1 - 0s - loss: 12238.4980
Epoch 200/900
1/1 - 0s - loss: 12171.3623
Epoch 201/900
1/1 - 0s - loss: 12124.2822
Epoch 202/900
1/1 - 0s - loss: 12158.7539
Epoch 203/900
1/1 - 0s - loss: 12144.2363
Epoch 204/900
1/1 - 0s - loss: 12015.5938
Epoch 205/900
1/1 - 0s - loss: 12035.4805
Epoch 206/900
1/1 - 0s - loss: 12014.2139
Epoch 207/900
1/1 - 0s - loss: 11966.5430
Epoch 208/900
1/1 - 0s - loss: 11845.8623
Epoch 209/900
1/1 - 0s - loss: 11789.7793
Epoch 210/900
1/1 - 0s - loss: 11833.0186
Epoch 211/900
1/1 - 0s - loss: 11694.6846
Epoch 212/900
1/1 - 0s - loss: 11676.6270
Epoch 213/900
1/1 - 0s - loss: 11650.6982
Epoch 214/900
1/1 - 0s - loss: 11581.3760
Epoch 215/900
1/1 - 0s - loss: 11507.5361
Epoch 216/900
1/1 - 0s - loss: 11561.0645
Epoch 217/900
1/1 - 0s - loss: 11435.1592
Epoch 218/900
1/1 - 0s - loss: 11398.4561
Epoch 219/900
1/1 - 0s - loss: 11367.9395
Epoch 220/900
1/1 - 0s - loss: 11323.1504
Epoch 221/900
1/1 - 0s - loss: 112

Epoch 394/900
1/1 - 0s - loss: 10479.5566
Epoch 395/900
1/1 - 0s - loss: 10550.6182
Epoch 396/900
1/1 - 0s - loss: 10707.9580
Epoch 397/900
1/1 - 0s - loss: 10263.1875
Epoch 398/900
1/1 - 0s - loss: 10158.7559
Epoch 399/900
1/1 - 0s - loss: 10387.0332
Epoch 400/900
1/1 - 0s - loss: 10353.5020
Epoch 401/900
1/1 - 0s - loss: 10495.5264
Epoch 402/900
1/1 - 0s - loss: 10126.6299
Epoch 403/900
1/1 - 0s - loss: 10190.8467
Epoch 404/900
1/1 - 0s - loss: 9969.0479
Epoch 405/900
1/1 - 0s - loss: 9898.0020
Epoch 406/900
1/1 - 0s - loss: 9961.9385
Epoch 407/900
1/1 - 0s - loss: 9706.8232
Epoch 408/900
1/1 - 0s - loss: 9852.4717
Epoch 409/900
1/1 - 0s - loss: 9752.1729
Epoch 410/900
1/1 - 0s - loss: 9561.6475
Epoch 411/900
1/1 - 0s - loss: 9492.8145
Epoch 412/900
1/1 - 0s - loss: 9399.4463
Epoch 413/900
1/1 - 0s - loss: 9261.0098
Epoch 414/900
1/1 - 0s - loss: 9298.5225
Epoch 415/900
1/1 - 0s - loss: 9194.2197
Epoch 416/900
1/1 - 0s - loss: 9029.5371
Epoch 417/900
1/1 - 0s - loss: 8934.0342
Epoch 

Epoch 592/900
1/1 - 0s - loss: 8013.7261
Epoch 593/900
1/1 - 0s - loss: 7892.8218
Epoch 594/900
1/1 - 0s - loss: 8102.4111
Epoch 595/900
1/1 - 0s - loss: 7774.1450
Epoch 596/900
1/1 - 0s - loss: 7889.2197
Epoch 597/900
1/1 - 0s - loss: 7687.2378
Epoch 598/900
1/1 - 0s - loss: 7650.5664
Epoch 599/900
1/1 - 0s - loss: 7715.2720
Epoch 600/900
1/1 - 0s - loss: 7596.1309
Epoch 601/900
1/1 - 0s - loss: 7678.6831
Epoch 602/900
1/1 - 0s - loss: 7536.2632
Epoch 603/900
1/1 - 0s - loss: 7593.2568
Epoch 604/900
1/1 - 0s - loss: 7488.8701
Epoch 605/900
1/1 - 0s - loss: 7572.7822
Epoch 606/900
1/1 - 0s - loss: 7467.1338
Epoch 607/900
1/1 - 0s - loss: 7515.3125
Epoch 608/900
1/1 - 0s - loss: 7426.9185
Epoch 609/900
1/1 - 0s - loss: 7449.0742
Epoch 610/900
1/1 - 0s - loss: 7366.0898
Epoch 611/900
1/1 - 0s - loss: 7376.3394
Epoch 612/900
1/1 - 0s - loss: 7317.4546
Epoch 613/900
1/1 - 0s - loss: 7332.6704
Epoch 614/900
1/1 - 0s - loss: 7277.3105
Epoch 615/900
1/1 - 0s - loss: 7269.6826
Epoch 616/900
1/

Epoch 792/900
1/1 - 0s - loss: 5272.0059
Epoch 793/900
1/1 - 0s - loss: 5262.8735
Epoch 794/900
1/1 - 0s - loss: 5252.7842
Epoch 795/900
1/1 - 0s - loss: 5243.0161
Epoch 796/900
1/1 - 0s - loss: 5231.8184
Epoch 797/900
1/1 - 0s - loss: 5224.2773
Epoch 798/900
1/1 - 0s - loss: 5214.0874
Epoch 799/900
1/1 - 0s - loss: 5206.4165
Epoch 800/900
1/1 - 0s - loss: 5195.2671
Epoch 801/900
1/1 - 0s - loss: 5185.4058
Epoch 802/900
1/1 - 0s - loss: 5174.9473
Epoch 803/900
1/1 - 0s - loss: 5163.2397
Epoch 804/900
1/1 - 0s - loss: 5155.2104
Epoch 805/900
1/1 - 0s - loss: 5145.7720
Epoch 806/900
1/1 - 0s - loss: 5136.0200
Epoch 807/900
1/1 - 0s - loss: 5126.0083
Epoch 808/900
1/1 - 0s - loss: 5117.6958
Epoch 809/900
1/1 - 0s - loss: 5106.4800
Epoch 810/900
1/1 - 0s - loss: 5098.5361
Epoch 811/900
1/1 - 0s - loss: 5088.9033
Epoch 812/900
1/1 - 0s - loss: 5078.3599
Epoch 813/900
1/1 - 0s - loss: 5070.0503
Epoch 814/900
1/1 - 0s - loss: 5060.1250
Epoch 815/900
1/1 - 0s - loss: 5051.1064
Epoch 816/900
1/

In [93]:
x_input = np.array([710, 578, 465])
temp_input = list(x_input)
lst_output = []
i=0
while(i<10):
    if(len(temp_input)>3):
        x_input = np.array(temp_input[1:])
        print("{} day input {}".format(i,x_input))
        x_input = x_input.reshape((1, n_step, n_features))
        yhat = model.predict(x_input, verbose=0)
        print("{} day output {}".format(i,yhat))
        temp_input.append(yhat[0][0])
        temp_input = temp_input[1:]
        lst_output.append(yhat[0][0])
        i=i+1
    else:
        x_input = x_input.reshape((1, n_step, n_features))
        yhat = model.predict(x_input, verbose=0)
        print(yhat[0])
        temp_input.append(yhat[0][0])
        lst_output.append(yhat[0][0])
        i=i+1
        
print(lst_output)

[456.6195 429.6551]
1 day input [578.         465.         456.61950684]
1 day output [[563.30646 562.69885]]
2 day input [465.         456.61950684 563.30645752]
2 day output [[436.01117 445.3204 ]]
3 day input [456.6195  563.30646 436.01117]
3 day output [[407.79837 419.99564]]
4 day input [563.30646 436.01117 407.79837]
4 day output [[483.24246 510.83878]]
5 day input [436.01117 407.79837 483.24246]
5 day output [[393.73618 406.1843 ]]
6 day input [407.79837 483.24246 393.73618]
6 day output [[610.54614 615.5623 ]]
7 day input [483.24246 393.73618 610.54614]
7 day output [[558.81537 590.6183 ]]
8 day input [393.73618 610.54614 558.81537]
8 day output [[520.19543 526.64886]]
9 day input [610.54614 558.81537 520.19543]
9 day output [[473.1392  489.92142]]
[456.6195, 563.30646, 436.01117, 407.79837, 483.24246, 393.73618, 610.54614, 558.81537, 520.19543, 473.1392]


In [94]:
Pos_pred = lst_output
Pos_pred

[456.6195,
 563.30646,
 436.01117,
 407.79837,
 483.24246,
 393.73618,
 610.54614,
 558.81537,
 520.19543,
 473.1392]

# Neg LSTM

In [95]:
def prepare_data(data,n_step):
    x,y=[],[]
    for i in range(len(data)):
        end_ix = i + n_step
        if end_ix > len(data)-1:
            break
        seq_x, seq_y = data[i:end_ix], data[end_ix]
        x.append(seq_x)
        y.append(seq_y)
    return np.array(x), np.array(y)

In [8]:
Neg_data = data.Neg
n_step = 5
x,y = prepare_data(Neg_data, n_step)

In [9]:
print(x)

[[ 88  88  88  10  30]
 [ 88  88  10  30  50]
 [ 88  10  30  50  67]
 [ 10  30  50  67  67]
 [ 30  50  67  67  84]
 [ 50  67  67  84  96]
 [ 67  67  84  96 109]
 [ 67  84  96 109  82]
 [ 84  96 109  82  56]
 [ 96 109  82  56  29]
 [109  82  56  29  32]
 [ 82  56  29  32  93]
 [ 56  29  32  93  60]
 [ 29  32  93  60  43]
 [ 32  93  60  43  43]
 [ 93  60  43  43  26]
 [ 60  43  43  26  20]
 [ 43  43  26  20  20]
 [ 43  26  20  20  14]
 [ 26  20  20  14 107]
 [ 20  20  14 107  33]
 [ 20  14 107  33  60]
 [ 14 107  33  60 207]
 [107  33  60 207 115]
 [ 33  60 207 115  88]
 [ 60 207 115  88 321]
 [207 115  88 321  55]
 [115  88 321  55 105]
 [ 88 321  55 105  62]]


In [10]:
print(y)

[ 50  67  67  84  96 109  82  56  29  32  93  60  43  43  26  20  20  14
 107  33  60 207 115  88 321  55 105  62  73]


In [98]:
x.shape

(29, 5)

In [99]:
n_features = 1
x = x.reshape((x.shape[0], x.shape[1], n_features))

In [100]:
x.shape

(29, 5, 1)

In [102]:
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_step, n_features)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
model.fit(x,y,epochs=200, verbose=1)

Epoch 1/200
1/1 [==============================] - 0s 16ms/step - loss: 9407.4971
Epoch 2/200
1/1 [==============================] - 0s 5ms/step - loss: 9357.7441
Epoch 3/200
1/1 [==============================] - 0s 1ms/step - loss: 9303.9893
Epoch 4/200
1/1 [==============================] - 0s 1ms/step - loss: 9244.7305
Epoch 5/200
1/1 [==============================] - 0s 2ms/step - loss: 9178.2012
Epoch 6/200
1/1 [==============================] - 0s 1ms/step - loss: 9102.8115
Epoch 7/200
1/1 [==============================] - 0s 8ms/step - loss: 9016.8633
Epoch 8/200
1/1 [==============================] - 0s 0s/step - loss: 8915.8330
Epoch 9/200
1/1 [==============================] - 0s 4ms/step - loss: 8794.1650
Epoch 10/200
1/1 [==============================] - 0s 996us/step - loss: 8643.9092
Epoch 11/200
1/1 [==============================] - 0s 0s/step - loss: 8453.6553
Epoch 12/200
1/1 [==============================] - 0s 0s/step - loss: 8214.0723
Epoch 13/200
1/1 [=======

In [105]:
x_input = np.array([321, 55, 105, 62, 73])
temp_input = list(x_input)
lst_output = []
i=0
while(i<10):
    if(len(temp_input)>5):
        x_input = np.array(temp_input[1:])
        print("{} day input {}".format(i,x_input))
        x_input = x_input.reshape((1, n_step, n_features))
        yhat = model.predict(x_input, verbose=0)
        print("{} day output {}".format(i,yhat))
        temp_input.append(yhat[0][0])
        temp_input = temp_input[1:]
        lst_output.append(yhat[0][0])
        i=i+1
    else:
        x_input = x_input.reshape((1, n_step, n_features))
        yhat = model.predict(x_input, verbose=0)
        print(yhat[0])
        temp_input.append(yhat[0][0])
        lst_output.append(yhat[0][0])
        i=i+1
        
print(lst_output)

[290.81378]
1 day input [ 55.         105.          62.          73.         290.81378174]
1 day output [[64.176605]]
2 day input [105.          62.          73.         290.81378174  64.17660522]
2 day output [[45.684715]]
3 day input [ 62.          73.         290.81378174  64.17660522  45.68471527]
3 day output [[508.02658]]
4 day input [ 73.         290.81378174  64.17660522  45.68471527 508.02658081]
4 day output [[129.1446]]
5 day input [290.81378   64.176605  45.684715 508.02658  129.1446  ]
5 day output [[180.17352]]
6 day input [ 64.176605  45.684715 508.02658  129.1446   180.17352 ]
6 day output [[838.10846]]
7 day input [ 45.684715 508.02658  129.1446   180.17352  838.10846 ]
7 day output [[411.70114]]
8 day input [508.02658 129.1446  180.17352 838.10846 411.70114]
8 day output [[772.20514]]
9 day input [129.1446  180.17352 838.10846 411.70114 772.20514]
9 day output [[1397.2137]]
[290.81378, 64.176605, 45.684715, 508.02658, 129.1446, 180.17352, 838.10846, 411.70114, 772.205

In [106]:
Neg_pred = lst_output
Neg_pred

[290.81378,
 64.176605,
 45.684715,
 508.02658,
 129.1446,
 180.17352,
 838.10846,
 411.70114,
 772.20514,
 1397.2137]

# Neu LSTM

In [107]:
def prepare_data(data,n_step):
    x,y=[],[]
    for i in range(len(data)):
        end_ix = i + n_step
        if end_ix > len(data)-1:
            break
        seq_x, seq_y = data[i:end_ix], data[end_ix]
        x.append(seq_x)
        y.append(seq_y)
    return np.array(x), np.array(y)

In [11]:
Neu_data = data.Neu
n_step = 3
x,y = prepare_data(Neu_data, n_step)

In [12]:
print(x)

[[406 463 520]
 [463 520 236]
 [520 236 343]
 [236 343 450]
 [343 450 397]
 [450 397 397]
 [397 397 344]
 [397 344 419]
 [344 419 495]
 [419 495 617]
 [495 617 739]
 [617 739 466]
 [739 466 660]
 [466 660 351]
 [660 351 808]
 [351 808 460]
 [808 460 460]
 [460 460 113]
 [460 113 231]
 [113 231 231]
 [231 231 350]
 [231 350 529]
 [350 529 484]
 [529 484 429]
 [484 429 204]
 [429 204 593]
 [204 593 522]
 [593 522 304]
 [522 304 286]
 [304 286 184]
 [286 184 360]]


In [13]:
print(y)

[236 343 450 397 397 344 419 495 617 739 466 660 351 808 460 460 113 231
 231 350 529 484 429 204 593 522 304 286 184 360 462]


In [111]:
x.shape

(31, 3)

In [112]:
n_features = 1
x = x.reshape((x.shape[0], x.shape[1], n_features))

In [113]:
x.shape

(31, 3, 1)

In [115]:
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_step, n_features)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
model.fit(x,y,epochs=600, verbose=1)

Epoch 1/600
1/1 [==============================] - 0s 0s/step - loss: 206697.8906
Epoch 2/600
1/1 [==============================] - 0s 0s/step - loss: 204177.7656
Epoch 3/600
1/1 [==============================] - 0s 0s/step - loss: 201272.6406
Epoch 4/600
1/1 [==============================] - 0s 2ms/step - loss: 198098.0781
Epoch 5/600
1/1 [==============================] - 0s 0s/step - loss: 195689.4531
Epoch 6/600
1/1 [==============================] - 0s 1ms/step - loss: 193856.3438
Epoch 7/600
1/1 [==============================] - 0s 4ms/step - loss: 191957.5781
Epoch 8/600
1/1 [==============================] - 0s 0s/step - loss: 190381.2031
Epoch 9/600
1/1 [==============================] - 0s 2ms/step - loss: 188953.1875
Epoch 10/600
1/1 [==============================] - 0s 3ms/step - loss: 187681.4531
Epoch 11/600
1/1 [==============================] - 0s 3ms/step - loss: 186549.5312
Epoch 12/600
1/1 [==============================] - 0s 997us/step - loss: 185435.7812
Epoc

1/1 [==============================] - 0s 2ms/step - loss: 6771.9189
Epoch 197/600
1/1 [==============================] - 0s 2ms/step - loss: 6707.4556
Epoch 198/600
1/1 [==============================] - 0s 3ms/step - loss: 8925.3525
Epoch 199/600
1/1 [==============================] - 0s 1ms/step - loss: 6839.6626
Epoch 200/600
1/1 [==============================] - 0s 1ms/step - loss: 6513.0205
Epoch 201/600
1/1 [==============================] - 0s 999us/step - loss: 6266.2651
Epoch 202/600
1/1 [==============================] - 0s 3ms/step - loss: 6408.4673
Epoch 203/600
1/1 [==============================] - 0s 10ms/step - loss: 5967.6753
Epoch 204/600
1/1 [==============================] - 0s 9ms/step - loss: 6129.8677
Epoch 205/600
1/1 [==============================] - 0s 7ms/step - loss: 6016.6313
Epoch 206/600
1/1 [==============================] - 0s 0s/step - loss: 5544.0820
Epoch 207/600
1/1 [==============================] - 0s 1ms/step - loss: 5736.9507
Epoch 208/600
1/

Epoch 294/600
1/1 [==============================] - 0s 1ms/step - loss: 20549.6777
Epoch 295/600
1/1 [==============================] - 0s 2ms/step - loss: 20159.6758
Epoch 296/600
1/1 [==============================] - 0s 1000us/step - loss: 19855.4785
Epoch 297/600
1/1 [==============================] - 0s 2ms/step - loss: 19546.4141
Epoch 298/600
1/1 [==============================] - 0s 998us/step - loss: 19350.4160
Epoch 299/600
1/1 [==============================] - 0s 4ms/step - loss: 19155.4043
Epoch 300/600
1/1 [==============================] - 0s 5ms/step - loss: 18557.6758
Epoch 301/600
1/1 [==============================] - 0s 3ms/step - loss: 17894.1973
Epoch 302/600
1/1 [==============================] - 0s 997us/step - loss: 17576.3477
Epoch 303/600
1/1 [==============================] - 0s 1ms/step - loss: 17335.7520
Epoch 304/600
1/1 [==============================] - 0s 2ms/step - loss: 17100.7246
Epoch 305/600
1/1 [==============================] - 0s 998us/step - 

1/1 [==============================] - 0s 0s/step - loss: 2249.1084
Epoch 490/600
1/1 [==============================] - 0s 3ms/step - loss: 2244.3860
Epoch 491/600
1/1 [==============================] - 0s 3ms/step - loss: 2239.7188
Epoch 492/600
1/1 [==============================] - 0s 2ms/step - loss: 2234.8184
Epoch 493/600
1/1 [==============================] - 0s 4ms/step - loss: 2230.0891
Epoch 494/600
1/1 [==============================] - 0s 2ms/step - loss: 2225.4543
Epoch 495/600
1/1 [==============================] - 0s 6ms/step - loss: 2220.8730
Epoch 496/600
1/1 [==============================] - 0s 3ms/step - loss: 2216.1409
Epoch 497/600
1/1 [==============================] - 0s 4ms/step - loss: 2211.3225
Epoch 498/600
1/1 [==============================] - 0s 5ms/step - loss: 2207.0857
Epoch 499/600
1/1 [==============================] - ETA: 0s - loss: 2202.18 - 0s 5ms/step - loss: 2202.1804
Epoch 500/600
1/1 [==============================] - 0s 6ms/step - loss: 219

In [116]:
x_input = np.array([184, 360, 462])
temp_input = list(x_input)
lst_output = []
i=0
while(i<10):
    if(len(temp_input)>3):
        x_input = np.array(temp_input[1:])
        print("{} day input {}".format(i,x_input))
        x_input = x_input.reshape((1, n_step, n_features))
        yhat = model.predict(x_input, verbose=0)
        print("{} day output {}".format(i,yhat))
        temp_input.append(yhat[0][0])
        temp_input = temp_input[1:]
        lst_output.append(yhat[0][0])
        i=i+1
    else:
        x_input = x_input.reshape((1, n_step, n_features))
        yhat = model.predict(x_input, verbose=0)
        print(yhat[0])
        temp_input.append(yhat[0][0])
        lst_output.append(yhat[0][0])
        i=i+1
        
print(lst_output)

[417.01584]
1 day input [360.         462.         417.01583862]
1 day output [[358.232]]
2 day input [462.         417.01583862 358.23199463]
2 day output [[402.14514]]
3 day input [417.01584 358.232   402.14514]
3 day output [[464.46533]]
4 day input [358.232   402.14514 464.46533]
4 day output [[387.69647]]
5 day input [402.14514 464.46533 387.69647]
5 day output [[344.64227]]
6 day input [464.46533 387.69647 344.64227]
6 day output [[360.93027]]
7 day input [387.69647 344.64227 360.93027]
7 day output [[456.55478]]
8 day input [344.64227 360.93027 456.55478]
8 day output [[595.30206]]
9 day input [360.93027 456.55478 595.30206]
9 day output [[654.3228]]
[417.01584, 358.232, 402.14514, 464.46533, 387.69647, 344.64227, 360.93027, 456.55478, 595.30206, 654.3228]


In [117]:
Neu_pred = lst_output
Neu_pred

[417.01584,
 358.232,
 402.14514,
 464.46533,
 387.69647,
 344.64227,
 360.93027,
 456.55478,
 595.30206,
 654.3228]

In [118]:
D = list(zip(Pos_pred,Neg_pred,Neu_pred))

In [119]:
final_pred = pd.DataFrame(D,columns=['Pos_pred','Neg_pred','Neu_pred'])
final_pred

Pos_pred     Neg_pred    Neu_pred
0  456.619507   290.813782  417.015839
1  563.306458    64.176605  358.231995
2  436.011169    45.684715  402.145142
3  407.798370   508.026581  464.465332
4  483.242462   129.144608  387.696472
5  393.736176   180.173523  344.642273
6  610.546143   838.108459  360.930267
7  558.815369   411.701141  456.554779
8  520.195435   772.205139  595.302063
9  473.139191  1397.213745  654.322815

In [120]:
final_pred.to_csv(r'C:\Users\asus\Desktop\Hashtag WD\Cricket_Pred_LSTM.csv',index=False)

In [3]:
Sentiment = pd.read_csv("Cricket_Pred_LSTM.csv")

In [4]:
Sentiment

Pos_pred     Neg_pred    Neu_pred Sentiment
0  456.619507   290.813782  417.015839  Positive
1  563.306457    64.176605  358.231995  Positive
2  436.011169    45.684715  402.145142  Positive
3  407.798370   508.026581  464.465332  Negative
4  483.242462   129.144608  387.696472  Positive
5  393.736176   180.173523  344.642273  Positive
6  610.546143   838.108459  360.930267  Negative
7  558.815369   411.701141  456.554779  Positive
8  520.195435   772.205139  595.302063  Negative
9  473.139191  1397.213745  654.322815  Negative

In [5]:
Actual_sentiment = pd.read_csv("Cricket_Actual_Sentiment.csv")

In [6]:
Actual_sentiment

date  Pos  Neg  Neu Sentiment
0  21-Apr-21  589  103  308  Positive
1  22-Apr-21  512   89  399  Positive
2  23-Apr-21  659   58  283  Positive
3  24-Apr-21  240  157  603   Neutral
4  25-Apr-21  702  198  100  Positive
5  26-Apr-21  489  212  299  Positive
6  27-Apr-21  270  207  523   Neutral
7  28-Apr-21  499  107  394  Positive
8  29-Apr-21  427  137  436   Neutral
9  30-Apr-21  324  278  398   Neutral

In [7]:
diff_Pos=abs(Sentiment.Pos_pred-Actual_sentiment.Pos)
MAPE_Pos=np.mean(diff_Pos/Actual_sentiment.Pos)*100
print("MAPE for Positive :",MAPE_Pos)

diff_Neg=abs(Sentiment.Neg_pred-Actual_sentiment.Neg)
MAPE_Neg=np.mean(diff_Neg/Actual_sentiment.Neg)*100
print("MAPE for Negative :",MAPE_Neg)

diff_Neu=abs(Sentiment.Neu_pred-Actual_sentiment.Neu)
MAPE_Neu=np.mean(diff_Neu/Actual_sentiment.Neu)*100
print("MAPE for Neutral :",MAPE_Neu)

MAPE for Positive : 39.28645902612145
MAPE for Negative : 196.07389253213583
MAPE for Neutral : 56.14539531284641


In [8]:
from sklearn.metrics import confusion_matrix

In [9]:
matrix=confusion_matrix(Actual_sentiment.Sentiment,Sentiment.Sentiment,labels=["Positive","Negative","Neutral"])
print("confusion matrix : \n",matrix)

confusion matrix : 
 [[6 0 0]
 [0 0 0]
 [0 4 0]]


In [10]:
dia_sum=np.trace(matrix)
all_sum=np.sum(matrix)

In [12]:
accuracy=(dia_sum/all_sum)*100
accuracy

60.0