In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten

In [4]:
data = pd.read_csv("PoliticsData.csv")
data.head()

Date      Type  Pos  Neg  Neu
0  18-03-2021  Politics  412  152  429
1  19-03-2021  Politics  654  121  225
2  20-03-2021  Politics  605  110  285
3  21-03-2021  Politics  296  505  198
4  22-03-2021  Politics  265  287  447

# Pos LSTM

In [5]:
def prepare_data(data,n_step):
    x,y=[],[]
    for i in range(len(data)):
        end_ix = i + n_step
        if end_ix > len(data)-1:
            break
        seq_x, seq_y = data[i:end_ix], data[end_ix]
        x.append(seq_x)
        y.append(seq_y)
    return np.array(x), np.array(y)

In [6]:
Pos_data = data.Pos
n_step = 3
x,y = prepare_data(Pos_data, n_step)

In [8]:
print(x)

[[412 654 605]
 [654 605 296]
 [605 296 265]
 [296 265 294]
 [265 294 196]
 [294 196 241]
 [196 241 216]
 [241 216 281]
 [216 281 311]
 [281 311 261]
 [311 261 261]
 [261 261 419]
 [261 419 419]
 [419 419 271]
 [419 271 328]
 [271 328 181]
 [328 181 295]
 [181 295 273]
 [295 273  74]
 [273  74 556]
 [ 74 556 522]
 [556 522 336]
 [522 336 246]
 [336 246 449]
 [246 449 219]
 [449 219 318]
 [219 318 200]
 [318 200 461]
 [200 461 381]
 [461 381 560]
 [381 560 417]]


In [9]:
print(y)

[296 265 294 196 241 216 281 311 261 261 419 419 271 328 181 295 273  74
 556 522 336 246 449 219 318 200 461 381 560 417 304]


In [8]:
x.shape

(31, 3)

In [9]:
n_features = 1
x = x.reshape((x.shape[0], x.shape[1], n_features))

In [10]:
x.shape

(31, 3, 1)

In [15]:
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_step, n_features)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(2))
model.compile(optimizer='adam', loss='mse')
model.fit(x,y,epochs=300, verbose=2)

Epoch 1/300
1/1 - 0s - loss: 108764.5625
Epoch 2/300
1/1 - 0s - loss: 107041.6875
Epoch 3/300
1/1 - 0s - loss: 105233.3594
Epoch 4/300
1/1 - 0s - loss: 103502.7188
Epoch 5/300
1/1 - 0s - loss: 101953.6719
Epoch 6/300
1/1 - 0s - loss: 100776.2578
Epoch 7/300
1/1 - 0s - loss: 99772.8906
Epoch 8/300
1/1 - 0s - loss: 98791.8516
Epoch 9/300
1/1 - 0s - loss: 97768.7422
Epoch 10/300
1/1 - 0s - loss: 96649.1172
Epoch 11/300
1/1 - 0s - loss: 95515.3906
Epoch 12/300
1/1 - 0s - loss: 94356.7734
Epoch 13/300
1/1 - 0s - loss: 93113.0938
Epoch 14/300
1/1 - 0s - loss: 91794.0625
Epoch 15/300
1/1 - 0s - loss: 90384.9062
Epoch 16/300
1/1 - 0s - loss: 88912.5547
Epoch 17/300
1/1 - 0s - loss: 87366.0469
Epoch 18/300
1/1 - 0s - loss: 85727.8203
Epoch 19/300
1/1 - 0s - loss: 83958.9844
Epoch 20/300
1/1 - 0s - loss: 82041.0234
Epoch 21/300
1/1 - 0s - loss: 79970.9688
Epoch 22/300
1/1 - 0s - loss: 77744.7734
Epoch 23/300
1/1 - 0s - loss: 75319.9219
Epoch 24/300
1/1 - 0s - loss: 72713.0781
Epoch 25/300
1/1 - 

1/1 - 0s - loss: 2624.3628
Epoch 202/300
1/1 - 0s - loss: 2583.3735
Epoch 203/300
1/1 - 0s - loss: 2547.0344
Epoch 204/300
1/1 - 0s - loss: 2517.9841
Epoch 205/300
1/1 - 0s - loss: 2487.7373
Epoch 206/300
1/1 - 0s - loss: 2460.2664
Epoch 207/300
1/1 - 0s - loss: 2434.8130
Epoch 208/300
1/1 - 0s - loss: 2415.5186
Epoch 209/300
1/1 - 0s - loss: 2400.9397
Epoch 210/300
1/1 - 0s - loss: 2403.8191
Epoch 211/300
1/1 - 0s - loss: 2430.7183
Epoch 212/300
1/1 - 0s - loss: 2479.1689
Epoch 213/300
1/1 - 0s - loss: 2456.6851
Epoch 214/300
1/1 - 0s - loss: 2324.1069
Epoch 215/300
1/1 - 0s - loss: 2227.0620
Epoch 216/300
1/1 - 0s - loss: 2275.2737
Epoch 217/300
1/1 - 0s - loss: 2330.2656
Epoch 218/300
1/1 - 0s - loss: 2276.1038
Epoch 219/300
1/1 - 0s - loss: 2160.5427
Epoch 220/300
1/1 - 0s - loss: 2143.1589
Epoch 221/300
1/1 - 0s - loss: 2205.9966
Epoch 222/300
1/1 - 0s - loss: 2214.5703
Epoch 223/300
1/1 - 0s - loss: 2147.5942
Epoch 224/300
1/1 - 0s - loss: 2081.0293
Epoch 225/300
1/1 - 0s - loss:

In [16]:
x_input = np.array([560, 417, 304])
temp_input = list(x_input)
lst_output = []
i=0
while(i<10):
    if(len(temp_input)>3):
        x_input = np.array(temp_input[1:])
        print("{} day input {}".format(i,x_input))
        x_input = x_input.reshape((1, n_step, n_features))
        yhat = model.predict(x_input, verbose=0)
        print("{} day output {}".format(i,yhat))
        temp_input.append(yhat[0][0])
        temp_input = temp_input[1:]
        lst_output.append(yhat[0][0])
        i=i+1
    else:
        x_input = x_input.reshape((1, n_step, n_features))
        yhat = model.predict(x_input, verbose=0)
        print(yhat[0])
        temp_input.append(yhat[0][0])
        lst_output.append(yhat[0][0])
        i=i+1
        
print(lst_output)

[422.57336 499.9065 ]
1 day input [417.         304.         422.57336426]
1 day output [[198.56592 216.2618 ]]
2 day input [304.         422.57336426 198.56591797]
2 day output [[366.07407 356.39893]]
3 day input [422.57336 198.56592 366.07407]
3 day output [[236.75346 275.25183]]
4 day input [198.56592 366.07407 236.75346]
4 day output [[360.02014 388.24408]]
5 day input [366.07407 236.75346 360.02014]
5 day output [[190.46527 194.3125 ]]
6 day input [236.75346 360.02014 190.46527]
6 day output [[341.3197  344.37253]]
7 day input [360.02014 190.46527 341.3197 ]
7 day output [[282.8282 347.199 ]]
8 day input [190.46527 341.3197  282.8282 ]
8 day output [[171.38878 166.8547 ]]
9 day input [341.3197  282.8282  171.38878]
9 day output [[281.79218 307.41666]]
[422.57336, 198.56592, 366.07407, 236.75346, 360.02014, 190.46527, 341.3197, 282.8282, 171.38878, 281.79218]


In [17]:
Pos_pred = lst_output

In [18]:
Pos_pred

[422.57336,
 198.56592,
 366.07407,
 236.75346,
 360.02014,
 190.46527,
 341.3197,
 282.8282,
 171.38878,
 281.79218]

# Neg LSTM

In [22]:
def prepare_data(data,n_step):
    x,y=[],[]
    for i in range(len(data)):
        end_ix = i + n_step
        if end_ix > len(data)-1:
            break
        seq_x, seq_y = data[i:end_ix], data[end_ix]
        x.append(seq_x)
        y.append(seq_y)
    return np.array(x), np.array(y)

In [10]:
Neg_data = data.Neg
n_step = 3
x,y = prepare_data(Neg_data, n_step)

In [11]:
print(x)

[[152 121 110]
 [121 110 505]
 [110 505 287]
 [505 287 149]
 [287 149  67]
 [149  67 358]
 [ 67 358 298]
 [358 298 286]
 [298 286 213]
 [286 213 252]
 [213 252 252]
 [252 252 222]
 [252 222 222]
 [222 222 346]
 [222 346 162]
 [346 162 540]
 [162 540 359]
 [540 359 287]
 [359 287 340]
 [287 340 121]
 [340 121 288]
 [121 288 326]
 [288 326 210]
 [326 210 189]
 [210 189 119]
 [189 119 327]
 [119 327 245]
 [327 245 209]
 [245 209 532]
 [209 532 304]
 [532 304 373]]


In [12]:
print(y)

[505 287 149  67 358 298 286 213 252 252 222 222 346 162 540 359 287 340
 121 288 326 210 189 119 327 245 209 532 304 373 439]


In [24]:
x.shape

(31, 3)

In [25]:
n_features = 1
x = x.reshape((x.shape[0], x.shape[1], n_features))

In [26]:
x.shape

(31, 3, 1)

In [28]:
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_step, n_features)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(2))
model.compile(optimizer='adam', loss='mse')
model.fit(x,y,epochs=300, verbose=1)

Epoch 1/300
1/1 [==============================] - 0s 7ms/step - loss: 100625.9453
Epoch 2/300
1/1 [==============================] - 0s 6ms/step - loss: 98761.6875
Epoch 3/300
1/1 [==============================] - 0s 0s/step - loss: 97306.8828
Epoch 4/300
1/1 [==============================] - 0s 2ms/step - loss: 96397.1797
Epoch 5/300
1/1 [==============================] - 0s 2ms/step - loss: 95623.5703
Epoch 6/300
1/1 [==============================] - 0s 995us/step - loss: 94871.9531
Epoch 7/300
1/1 [==============================] - 0s 2ms/step - loss: 94008.3203
Epoch 8/300
1/1 [==============================] - 0s 996us/step - loss: 92984.6797
Epoch 9/300
1/1 [==============================] - 0s 1ms/step - loss: 91887.5703
Epoch 10/300
1/1 [==============================] - 0s 996us/step - loss: 90716.5625
Epoch 11/300
1/1 [==============================] - 0s 4ms/step - loss: 89429.8203
Epoch 12/300
1/1 [==============================] - 0s 3ms/step - loss: 88110.8984
Epoch 1

1/1 [==============================] - 0s 1ms/step - loss: 6487.8008
Epoch 101/300
1/1 [==============================] - 0s 3ms/step - loss: 6317.7866
Epoch 102/300
1/1 [==============================] - 0s 1ms/step - loss: 5895.9458
Epoch 103/300
1/1 [==============================] - 0s 3ms/step - loss: 6144.1592
Epoch 104/300
1/1 [==============================] - 0s 3ms/step - loss: 5553.0869
Epoch 105/300
1/1 [==============================] - 0s 0s/step - loss: 5915.3467
Epoch 106/300
1/1 [==============================] - 0s 0s/step - loss: 5732.7007
Epoch 107/300
1/1 [==============================] - 0s 2ms/step - loss: 5594.9536
Epoch 108/300
1/1 [==============================] - 0s 2ms/step - loss: 5238.8252
Epoch 109/300
1/1 [==============================] - 0s 4ms/step - loss: 5124.7227
Epoch 110/300
1/1 [==============================] - 0s 4ms/step - loss: 5119.5566
Epoch 111/300
1/1 [==============================] - 0s 2ms/step - loss: 4956.5122
Epoch 112/300
1/1 [=

1/1 [==============================] - 0s 1ms/step - loss: 0.7740


In [29]:
x_input = np.array([304, 373, 439])
temp_input = list(x_input)
lst_output = []
i=0
while(i<10):
    if(len(temp_input)>3):
        x_input = np.array(temp_input[1:])
        print("{} day input {}".format(i,x_input))
        x_input = x_input.reshape((1, n_step, n_features))
        yhat = model.predict(x_input, verbose=0)
        print("{} day output {}".format(i,yhat))
        temp_input.append(yhat[0][0])
        temp_input = temp_input[1:]
        lst_output.append(yhat[0][0])
        i=i+1
    else:
        x_input = x_input.reshape((1, n_step, n_features))
        yhat = model.predict(x_input, verbose=0)
        print(yhat[0])
        temp_input.append(yhat[0][0])
        lst_output.append(yhat[0][0])
        i=i+1
        
print(lst_output)

[138.86958  119.178635]
1 day input [373.         439.         138.86958313]
1 day output [[389.64886 349.04633]]
2 day input [439.         138.86958313 389.64886475]
2 day output [[384.5437  388.07236]]
3 day input [138.86958 389.64886 384.5437 ]
3 day output [[201.89235 190.05132]]
4 day input [389.64886 384.5437  201.89235]
4 day output [[247.06026 232.20772]]
5 day input [384.5437  201.89235 247.06026]
5 day output [[210.27017 225.99628]]
6 day input [201.89235 247.06026 210.27017]
6 day output [[330.78317 326.5515 ]]
7 day input [247.06026 210.27017 330.78317]
7 day output [[160.48041 156.46048]]
8 day input [210.27017 330.78317 160.48041]
8 day output [[536.4602 537.3942]]
9 day input [330.78317 160.48041 536.4602 ]
9 day output [[360.36566 363.28513]]
[138.86958, 389.64886, 384.5437, 201.89235, 247.06026, 210.27017, 330.78317, 160.48041, 536.4602, 360.36566]


In [30]:
Neg_pred = lst_output

In [31]:
Neg_pred

[138.86958,
 389.64886,
 384.5437,
 201.89235,
 247.06026,
 210.27017,
 330.78317,
 160.48041,
 536.4602,
 360.36566]

# Neu LSTM

In [32]:
def prepare_data(data,n_step):
    x,y=[],[]
    for i in range(len(data)):
        end_ix = i + n_step
        if end_ix > len(data)-1:
            break
        seq_x, seq_y = data[i:end_ix], data[end_ix]
        x.append(seq_x)
        y.append(seq_y)
    return np.array(x), np.array(y)

In [13]:
Neu_data = data.Neu
n_step = 3
x,y = prepare_data(Neu_data, n_step)

In [14]:
print(x)

[[429 225 285]
 [225 285 198]
 [285 198 447]
 [198 447 557]
 [447 557 736]
 [557 736 400]
 [736 400 486]
 [400 486 433]
 [486 433 476]
 [433 476 485]
 [476 485 485]
 [485 485 358]
 [485 358 358]
 [358 358 382]
 [358 382 510]
 [382 510 278]
 [510 278 336]
 [278 336 439]
 [336 439 586]
 [439 586 323]
 [586 323 189]
 [323 189 338]
 [189 338 544]
 [338 544 361]
 [544 361 662]
 [361 662 354]
 [662 354 554]
 [354 554 329]
 [554 329  86]
 [329  86 135]
 [ 86 135 210]]


In [15]:
print(y)

[198 447 557 736 400 486 433 476 485 485 358 358 382 510 278 336 439 586
 323 189 338 544 361 662 354 554 329  86 135 210 257]


In [35]:
x.shape

(31, 3)

In [36]:
n_features = 1
x = x.reshape((x.shape[0], x.shape[1], n_features))

In [37]:
x.shape

(31, 3, 1)

In [44]:
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_step, n_features)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(2))
model.compile(optimizer='adam', loss='mse')
model.fit(x,y,epochs=300, verbose=2)

Epoch 1/300
1/1 - 0s - loss: 169875.1875
Epoch 2/300
1/1 - 0s - loss: 168389.3125
Epoch 3/300
1/1 - 0s - loss: 166616.9062
Epoch 4/300
1/1 - 0s - loss: 164606.8125
Epoch 5/300
1/1 - 0s - loss: 162413.2188
Epoch 6/300
1/1 - 0s - loss: 159993.6562
Epoch 7/300
1/1 - 0s - loss: 157214.8594
Epoch 8/300
1/1 - 0s - loss: 154200.7344
Epoch 9/300
1/1 - 0s - loss: 151475.0938
Epoch 10/300
1/1 - 0s - loss: 148795.0781
Epoch 11/300
1/1 - 0s - loss: 145484.9062
Epoch 12/300
1/1 - 0s - loss: 141944.8750
Epoch 13/300
1/1 - 0s - loss: 138199.9531
Epoch 14/300
1/1 - 0s - loss: 134450.3125
Epoch 15/300
1/1 - 0s - loss: 130681.9141
Epoch 16/300
1/1 - 0s - loss: 126598.8203
Epoch 17/300
1/1 - 0s - loss: 122034.7734
Epoch 18/300
1/1 - 0s - loss: 116383.8984
Epoch 19/300
1/1 - 0s - loss: 109915.8281
Epoch 20/300
1/1 - 0s - loss: 104447.3125
Epoch 21/300
1/1 - 0s - loss: 98776.5625
Epoch 22/300
1/1 - 0s - loss: 93026.4453
Epoch 23/300
1/1 - 0s - loss: 87528.1797
Epoch 24/300
1/1 - 0s - loss: 81771.8906
Epoch

Epoch 201/300
1/1 - 0s - loss: 4158.6128
Epoch 202/300
1/1 - 0s - loss: 4023.7119
Epoch 203/300
1/1 - 0s - loss: 4005.0674
Epoch 204/300
1/1 - 0s - loss: 4025.6858
Epoch 205/300
1/1 - 0s - loss: 4027.6794
Epoch 206/300
1/1 - 0s - loss: 3962.0054
Epoch 207/300
1/1 - 0s - loss: 3870.3396
Epoch 208/300
1/1 - 0s - loss: 3815.8250
Epoch 209/300
1/1 - 0s - loss: 3822.7419
Epoch 210/300
1/1 - 0s - loss: 3814.9885
Epoch 211/300
1/1 - 0s - loss: 3771.4895
Epoch 212/300
1/1 - 0s - loss: 3720.2180
Epoch 213/300
1/1 - 0s - loss: 3696.9260
Epoch 214/300
1/1 - 0s - loss: 3679.1003
Epoch 215/300
1/1 - 0s - loss: 3638.9124
Epoch 216/300
1/1 - 0s - loss: 3610.4524
Epoch 217/300
1/1 - 0s - loss: 3587.3467
Epoch 218/300
1/1 - 0s - loss: 3557.4028
Epoch 219/300
1/1 - 0s - loss: 3524.0188
Epoch 220/300
1/1 - 0s - loss: 3485.8704
Epoch 221/300
1/1 - 0s - loss: 3452.6418
Epoch 222/300
1/1 - 0s - loss: 3416.7822
Epoch 223/300
1/1 - 0s - loss: 3373.6414
Epoch 224/300
1/1 - 0s - loss: 3345.8882
Epoch 225/300
1/

In [45]:
x_input = np.array([135, 210, 257])
temp_input = list(x_input)
lst_output = []
i=0
while(i<10):
    if(len(temp_input)>3):
        x_input = np.array(temp_input[1:])
        print("{} day input {}".format(i,x_input))
        x_input = x_input.reshape((1, n_step, n_features))
        yhat = model.predict(x_input, verbose=0)
        print("{} day output {}".format(i,yhat))
        temp_input.append(yhat[0][0])
        temp_input = temp_input[1:]
        lst_output.append(yhat[0][0])
        i=i+1
    else:
        x_input = x_input.reshape((1, n_step, n_features))
        yhat = model.predict(x_input, verbose=0)
        print(yhat[0])
        temp_input.append(yhat[0][0])
        lst_output.append(yhat[0][0])
        i=i+1
        
print(lst_output)

[395.65732 390.31384]
1 day input [210.         257.         395.65731812]
1 day output [[513.3883 525.2297]]
2 day input [257.         395.65731812 513.38830566]
2 day output [[626.427 626.165]]
3 day input [395.65732 513.3883  626.427  ]
3 day output [[363.55826 369.78488]]
4 day input [513.3883  626.427   363.55826]
4 day output [[340.81174 329.53308]]
5 day input [626.427   363.55826 340.81174]
5 day output [[399.29034 415.6599 ]]
6 day input [363.55826 340.81174 399.29034]
6 day output [[575.51495 582.755  ]]
7 day input [340.81174 399.29034 575.51495]
7 day output [[281.76904 292.82974]]
8 day input [399.29034 575.51495 281.76904]
8 day output [[274.46936 256.44226]]
9 day input [575.51495 281.76904 274.46936]
9 day output [[185.25266 206.38431]]
[395.65732, 513.3883, 626.427, 363.55826, 340.81174, 399.29034, 575.51495, 281.76904, 274.46936, 185.25266]


In [46]:
Neu_pred = lst_output
Neu_pred

[395.65732,
 513.3883,
 626.427,
 363.55826,
 340.81174,
 399.29034,
 575.51495,
 281.76904,
 274.46936,
 185.25266]

In [47]:
D = list(zip(Pos_pred,Neg_pred,Neu_pred))

In [48]:
final_pred = pd.DataFrame(D,columns=['Pos_pred','Neg_pred','Neu_pred'])

In [49]:
final_pred

Pos_pred    Neg_pred    Neu_pred
0  422.573364  138.869583  395.657318
1  198.565918  389.648865  513.388306
2  366.074066  384.543701  626.427002
3  236.753464  201.892349  363.558258
4  360.020142  247.060257  340.811737
5  190.465271  210.270172  399.290344
6  341.319702  330.783173  575.514954
7  282.828186  160.480408  281.769043
8  171.388779  536.460205  274.469360
9  281.792175  360.365662  185.252655

In [50]:
final_pred.to_csv(r'C:\Users\asus\Desktop\Hashtag WD\Politics\Politics_Pred_LSTM_1.csv',index=False)

In [7]:
Sentiment = pd.read_csv("Politics_Pred_LSTM_1.csv")

In [8]:
Sentiment

Pos_pred    Neg_pred    Neu_pred Sentiment
0  422.573364  138.869583  395.657318  Positive
1  198.565918  389.648865  513.388306   Neutral
2  366.074066  384.543701  626.427002   Neutral
3  236.753464  201.892349  363.558258   Neutral
4  360.020142  247.060257  340.811737  Positive
5  190.465271  210.270172  399.290344   Neutral
6  341.319702  330.783173  575.514954   Neutral
7  282.828186  160.480408  281.769043  Positive
8  171.388779  536.460205  274.469360  Negative
9  281.792175  360.365662  185.252655  Negative

In [9]:
Actual_sentiment = pd.read_csv("Politics_Actual_Sentiment.csv")

In [10]:
Actual_sentiment

Date  Pos  Neg  Neu Sentiment
0  21-Apr-21  472  156  372  Positive
1  22-Apr-21  367  302  331  Positive
2  23-Apr-21  230  298  472   Neutral
3  24-Apr-21  384  104  512   Neutral
4  25-Apr-21  467  156  377  Positive
5  26-Apr-21  281  267  452   Neutral
6  27-Apr-21  330  102  568   Neutral
7  28-Apr-21  302  306  392   Neutral
8  29-Apr-21  212  427  361  Negative
9  30-Apr-21  522  256  222  Positive

In [11]:
diff_Pos=abs(Sentiment.Pos_pred-Actual_sentiment.Pos)
MAPE_Pos=np.mean(diff_Pos/Actual_sentiment.Pos)*100
print("MAPE for Positive :",MAPE_Pos)

diff_Neg=abs(Sentiment.Neg_pred-Actual_sentiment.Neg)
MAPE_Neg=np.mean(diff_Neg/Actual_sentiment.Neg)*100
print("MAPE for Negative :",MAPE_Neg)

diff_Neu=abs(Sentiment.Neu_pred-Actual_sentiment.Neu)
MAPE_Neu=np.mean(diff_Neu/Actual_sentiment.Neu)*100
print("MAPE for Neutral :",MAPE_Neu)

MAPE for Positive : 28.395289373918075
MAPE for Negative : 58.104689021710755
MAPE for Neutral : 21.439801283008634


In [12]:
from sklearn.metrics import confusion_matrix

In [13]:
matrix=confusion_matrix(Actual_sentiment.Sentiment,Sentiment.Sentiment,labels=["Positive","Negative","Neutral"])
print("confusion matrix : \n",matrix)

confusion matrix : 
 [[2 1 1]
 [0 1 0]
 [1 0 4]]


In [14]:
dia_sum=np.trace(matrix)
all_sum=np.sum(matrix)

In [15]:
accuracy=(dia_sum/all_sum)*100
accuracy

70.0

In [3]:
#pip install -U notebook-as-pdf

In [9]:
#pyppeteer-install

In [8]:
#jupyter nbconvert -to pdf Politics LSTM.ipynb

In [7]:
#pip install nbconvert